default_agent: mcp_server_spa
agents:
  mcp_server_spa:
    name: mcp_server_spa
    language: python
    node_version: '20'
    entrypoint: C:/Users/mispandana/agentcore-mcp-server/mcp_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\mispandana\agentcore-mcp-server
    aws:
      execution_role: arn:aws:iam::212499160857:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ccfe52f430
      execution_role_auto_create: false
      account: '212499160857'
      region: us-east-1
      ecr_repository: 212499160857.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-mcp_server_spa
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: mcp_server_spa-QHy4zABRHR
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:212499160857:runtime/mcp_server_spa-QHy4zABRHR
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-mcp_server_spa-builder
      execution_role: arn:aws:iam::212499160857:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ccfe52f430
      source_bucket: bedrock-agentcore-codebuild-sources-212499160857-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: mcp_server_spa_mem-nqK7kKFseE
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:212499160857:memory/mcp_server_spa_mem-nqK7kKFseE
      memory_name: mcp_server_spa_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
